spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    username: ${DB_USER:root}
    password: ${DB_PASS:123456}
    url: ${DB_URL:jdbc:mariadb://localhost:3306/demoday}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}