spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
      locations: classpath:/graphql/**/
      file-extensions: .graphqls
    path: /graphql
  datasource:
    username: ${DB_USER:root}
    password: ${DB_PASS:123456}
    url: ${DB_URL:jdbc:mariadb://localhost:3306/demoday}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
jwt:
  secret: ${JWT_SECRET:1234456789876545678i9876545678765456787654345676543456787654567876545678909876789}